### ISSUE TITLE
Spams installation

### ISSUE THREAD

**Issue by krimsonking1999** [daducci/AMICO#38]
Hi,

Sorry to write here because I know this is not supposed to be a help line. I have fought with this for a while and can't use AMICO if spams isn't installing correctly.    

I have tried on both on mac os and a fresh ubuntu 16.04 install and run into gcc errors on both of the os's.  I'll focus on Ubuntu because it is the easiest to re-create.  

I am working in Python2.7 and have installed both using anaconda and python-pip.  I have also installed numpy using pip install for the python-pip.  I have tried to address dependencies by installing build-essential, libatlas-dev, and libatlas3-base. In following the listed installation instructions I have ensured that I have libblas.so (actually libblas.so and libblas.so.3) and liblapack.so (actually liblapack.so.3 and liblapack_atlas.so.3 [I added 'lapack_atlas' to the libs in setup.py]) are in /usr/lib. I have run apt-get update to ensure I am on a stable build as well. 

For both prefix and build installation I run into some interesting errors.  

Main exit error: 'x86_64-linux-gnu-gcc' failed with exit status 1

Additional warnings and errors thrown:

1. cc1plus: warning command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++

2. spams/linalg/linalg.h:1680:10 error: expected '(' before '__builtin_isnan

3. Warning # warning using deprecated NumPy API

4. Warning: comparison between signed and unsigned integer expressions

Do you have any idea what could be going wrong?  

Thank you ,

Gary

**Comment by daducci** [comment]
Hi Gary,

I have a Mac and I'm not very familiar with Ubuntu. I remember I managed to install SPAMS on Ubuntu a few years ago (I think it was Ubuntu 14) on a test machine and the installation went really smoothly.

@gabknight and @davidrs06 do you have any experience as you are using Ubuntu?

Ale

**Comment by davidrs06** [comment]
I don't recall having any problem installing spams on Ubuntu 14.04. I think I followed the instructions in the INSTALL-package file, mainly running the following:
```
cd spams-python
python setup.py build

inst=<your-python-install-dir>
python setup.py install --prefix=$inst
```
There's a comment on Linux installations stating that there might be issues with the atlas module:
> carefully install atlas. For example on my ubuntu I had to do
>       apt-get install libatlas-dev libatlas3gf-base libatlas-3gf.so
>       If you don't have libblas.so and liblapack.so in /lib or /usr/lib,
>       you need to edit setup.py

But apparently you already addressed these... Could it be the compiler ?

**Comment by krimsonking1999** [comment]
Hi Ale,

Thank you for getting back to me.


I just got it to work!  I ended up installing everything on a centOS VM and was very careful with the atlas and blas installation.  I'm happy to put together a write up of installation and modules used incase this becomes a reoccurring issue.


Best,


Gary


________________________________

**Comment by learner0903** [comment]
Hi Gary,

I am having exactly the same problem. Could you please kindly share how you made it work? Did you still use libatlas-dev for atlas or did you build from their source? Thanks.

Ling

**Comment by krimsonking1999** [comment]
Hi Ling,

I just setup a new vm with this protocol, so it should work for you.  Let me know if you have any questions. 

In vmware I made a vm with the newest centOS .iso using GNOME desktop with the developer toolkit.  This vm should have 40 GB of space at least and at least 4 GB of ram.  The space fills up quickly and the RAM is required for the processing which apparently is very hungry.  Also, I couldn’t get it to work correctly when not installed on my main drive. 
Make sure to actually select the installation medium because I left it on auto and had two failed installations.  
sudo yum install = syi
Sudo = s

Syi open-vm-tools
Install python using sudo yum install python
Syi epel-release
Syi python-pip
Syi python-wheel
Sy upgrade python-setuptools
Sudo pip install –upgrade pip
S Pip install numpy
s Pip install setuptools –upgrade
Sudo pip install numpy
Syi python27-devel
S Yum update
Syi atlas-devel
Syi atlas-dev
Syi atlas
Syi blas
Syi blas-dev
Syi lapack
Syi lapack-devel
Syi python-devel
Sudo pip install ipython
Sudo pip install nibabel
Sudo pip install dipy
Sudo pip install nipy
Sudo pip intall scipy


Navigate to spams directory in downloads
In setup.py I also added ‘/usr/lib64’ but I’m not sure if that helped
Open terminal 
Sudo python setup.py install –prefix=

Spams was installed in my usr/lib/python2.7/site-packages directory and was importable.

**Comment by learner0903** [comment]
Hi Gary, 
Thank you so much indeed. I'll certainly give it a try! :)

**Comment by trislett** [comment]
I had the same issue on Ubuntu 16.04. Add a couple of brackets at line 1680 of spams/linalg/linalg.h and it should compile properly. I think it depends on which compiler you are using.

i.e.,
`
if (isnan(lambda)) {`

**Comment by daducci** [comment]
I tried just yesterday on a fresh Ubuntu 14.04, and the installation went through without any errors and without changing  a single line. Perhaps there's something different with Ubuntu 16.04; for instance, I was unable to install MrTrix on it and I had to revert to an older version (14.04 indeed).

Hope this helps!

**Comment by stevenydc** [comment]
I had same problem as OP and tried trislett's suggestion but it gave me more errors:

```
spams/decomp/decomp.h:2602:6: internal compiler error: Segmentation fault: 11
 void coreGroupIST(const Matrix<T>& G, Matrix<T>& RtDm,
      ^~~~~~~~~~~~

spams/decomp/decomp.h:2602:6: internal compiler error: Abort trap: 6
gcc-6: internal compiler error: Abort trap: 6 (program cc1plus)
```

I'm on Mac OS Sierra...  has anyone else figured out a solution?

**Comment by samuelstjean** [comment]
Well I was looking to see if you guys had problems with fortran array and numpy 1.12 again (I seem to have the same bug that crept up in 1.10 with the fortran ordering in my stuff), but anyway, the compiler issues are caused by recent gcc (starting with gcc 6 if memory serves) in which case you get a bracket/parenthesis error which prevents compilation. 

There are a set of unofficial patches for that over at https://aur.archlinux.org/cgit/aur.git/tree/python-spams.patch?h=python-spams-svn which makes it build on recent compiler and python 3 among other things, including recent mac version. 

I also personally maintain a patched version of that and some wheel files (no py 3.6 yet though) if it can be of some use over at https://github.com/samuelstjean/spams-python/releases. Pretty much the same as upstream + mentionned patches, so I can't offer support beyond that either. 

Although some people are working on conda packages (https://github.com/conda-forge/python-spams-feedstock/pull/1) at making it work with various blas/lapack version, this one should pick up whatever you have without needing atlas or the plain blas implementation.

**Comment by samuelstjean** [comment]
Completely forgot about the mac stuff, I also remember having a hard time making it work with mac at first, but Alessandro had a modified setup.py for that (it just deactivates openmp by removing -fopenmp from the link flags and other small stuff, I did get some segfaults with gcc before giving up) which is included in my set of patches, but is not found on the one I linked from the archlinux guys though.

**Comment by anbai106** [comment]
@stevenydc
I think your problem is the version of your gcc, gcc 6.0 does not work for this, try gcc-4.7, i had the same problem with my Mac, and use gcc4.9 and installed spams successfully, but the problem is 
when I run in python:
`import spams`
it gave me errors:

> Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/junhao.wen/anaconda2/lib/python2.7/site-packages/spams.py", line 6, in <module>
import spams_wrap
File "/Users/junhao.wen/anaconda2/lib/python2.7/site-packages/spams_wrap.py", line 24, in <module>
_spams_wrap = swig_import_helper()
File "/Users/junhao.wen/anaconda2/lib/python2.7/site-packages/spams_wrap.py", line 23, in swig_import_helper
return importlib.import_module('_spams_wrap')
File "/Users/junhao.wen/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
__import__(name)
ImportError: dynamic module does not define init function (init_spams_wrap)

Any idea????

I wrote an email to the author, they told me they will try to look at it.

Other information:

> MAC(10.11.6), with gcc(4.9.0), python 2.7, tried spams2.5 and 2.6, both the same errors

Thanks in advance

**Comment by deagaric** [comment]
Hi, I also have the same "dynamic module doe not define init function (init_spams_wrap)" error as anbai106 above. Has anyone managed to solve this? I have gcc 7.1.0, Python 2.7, and spams 2.6.

**Comment by MariaICL** [comment]
I get a different error when I try to import spams in python:

ImportError: /apps/software/anaconda/4.3.1/lib/python2.7/site-packages/_spams_wrap.so: undefined symbol: _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE

Any ideas?

**Comment by pangyuteng** [comment]
i had trouble installing `spams`, below is my installation steps for windows, likely would work for ubuntu if you switched the spams installation to a pre-built ver.
https://gist.github.com/pangyuteng/5df295faf19d7474d3c3e86b90c2654a

**Comment by lucilla7** [comment]
Hi,
I get two different errors with two different SPAMS versions:
on 2.6
```
  File "test_spams.py", line 3, in <module>
    import test_utils
  File "/venv/test/test_utils.py", line 2, in <module>
    import spams
  File "/venv/lib/python2.7/site-packages/spams.py", line 6, in <module>
    import spams_wrap
  File "/venv/lib/python2.7/site-packages/spams_wrap.py", line 24, in <module>
    _spams_wrap = swig_import_helper()
  File "/venv/lib/python2.7/site-packages/spams_wrap.py", line 23, in swig_import_helper
    return importlib.import_module('_spams_wrap')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: dlopen(/venv/lib/python2.7/site-packages/_spams_wrap.so, 2): Symbol not found: _GOMP_critical_end
  Referenced from: /venv/lib/python2.7/site-packages/_spams_wrap.so
  Expected in: flat namespace
 in /venv/lib/python2.7/site-packages/_spams_wrap.so

```
on 2.6.1:
```
spams_wrap.cpp: In function ‘PyObject* _wrap_sparseProject__SWIG_0(PyObject*, PyObject*)’:
spams_wrap.cpp:6092: internal compiler error: Segmentation fault: 11
Please submit a full bug report,
with preprocessed source if appropriate.
See <URL:http://developer.apple.com/bugreporter> for instructions.
lipo: can't figure out the architecture type of: /var/folders/24/sspghyxx6_9g3n9pcw5fqmk40000gn/T//ccTnVTaB.out
error: command 'gcc-4.2' failed with exit status 1
```

**Comment by samuelstjean** [comment]
That's most likely due to macos not having openmp by default, so either it needs to be deactivated or you have to install a gcc/clang version form scratch which has openmp, like iwht using homebrew for example.

It's still easier to just comment a few lines in the setup.py though, and amico remains pretty fast still. Anyway, those are the lines (or similar, 2.6 changed the setup.py ordering a bit)

```python
#if osname.startswith("macosx"):
#    cc_flags = ['-fPIC','-w'] # I deactivated -fopenmp as it does not work on clang by default
#    link_flags = ['']
```

I also put up a bunch of modified spams build without open mp by default (I think the ones for mac are built with openmp) if you want to try those instead of compiling and modifying stuff

https://github.com/samuelstjean/spams-python/releases/tag/v2.6

**Comment by lucilla7** [comment]
Thank you! Commenting the flags lines did the trick.

**Comment by daducci** [comment]
Duplicate of #68

**Comment by mayxx** [comment]
on mac os 
pip3 install spams-mkl
and I also tried  python setup.py install --prefix=<your-installation-dir>
can not install successfully 
failed with error code 1 in /private/var/folders/17/tkc9wcrs69s41dfd35mvr9f00000gn/T/pip-install-cp7xlyjs/spams-mkl/ 
how can I fix it
